import type { IncomingMessage, ServerResponse } from 'http';

export const data = [
  {
    idx: 0,
    title: '热门推荐',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'Dribbble',
        desc: '全球UI设计师作品秀社区',
        url: 'https://dribbble.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/dribbble.png',
      },
      {
        idx: 1,
        title: 'Behance',
        desc: 'Adobe旗下设计师创意视觉社区',
        url: 'https://www.behance.net/',
        logo: 'http://chuangzaoshi.com/assets/images/D/behance.png',
      },
      {
        idx: 2,
        title: 'Logopond',
        desc: '国外LOGO展示社区',
        url: 'http://logopond.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/logopond.png',
      },
      {
        idx: 3,
        title: 'Ello',
        desc: '创意工作者网络社区和资讯',
        url: 'https://ello.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/ello.png',
      },
      {
        idx: 4,
        title: 'MyFont',
        desc: '最新时尚的商业英文字体',
        url: 'http://www.myfonts.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/myfonts.png',
      },
      {
        idx: 5,
        title: '站酷',
        desc: '国内综合设计展示平台',
        url: 'http://www.zcool.com.cn/',
        logo: 'http://chuangzaoshi.com/assets/images/D/zool.png',
      },
      {
        idx: 6,
        title: '摹客',
        desc: '设计协作，用摹客。100人团队免费使用',
        url: 'https://www.mockplus.cn/idoc-ui/?hmsr=chuangzaoshi',
        logo: 'http://chuangzaoshi.com/assets/images/D/mockplus.png',
      },
      {
        idx: 7,
        title: 'Sketchfab',
        desc: '全球最极致3D设计模型在线展示平台',
        url: 'https://sketchfab.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/sketchfab.png',
      },
      {
        idx: 8,
        title: 'AdobeColor',
        desc: '非常便捷的在线配色网站',
        url: 'https://color.adobe.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/adobecolor.png',
      },
      {
        idx: 9,
        title: 'lapa',
        desc: '优秀LandingPage落地页收集',
        url: 'http://lapa.ninja/',
        logo: 'http://chuangzaoshi.com/assets/images/D/lapa.png',
      },
      {
        idx: 10,
        title: 'Fubiz',
        desc: '法国每日新鲜创意灵感分享',
        url: 'http://www.fubiz.net/',
        logo: 'http://chuangzaoshi.com/assets/images/D/fubiz.png',
      },
      {
        idx: 11,
        title: 'UIgradients',
        desc: '简洁舒服的渐变配色',
        url: 'http://uigradients.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uigradients.png',
      },
      {
        idx: 12,
        title: 'Vimeo动画',
        desc: '视频分享平台创意动画频道[需要翻墙]',
        url: 'https://vimeo.com/categories/animation',
        logo: 'http://chuangzaoshi.com/assets/images/D/vimeo.png',
      },
      {
        idx: 13,
        title: 'MalliGraphics',
        desc: '精心挑选的样机效果Mockup模板',
        url: 'https://malli.graphics/',
        logo: 'http://chuangzaoshi.com/assets/images/D/malli.png',
      },
      {
        idx: 14,
        title: 'MyModernMet',
        desc: '视觉创意和艺术爱好者网站',
        url: 'http://mymodernmet.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/mymodernmet.png',
      },
      {
        idx: 15,
        title: 'Nucleo',
        desc: '免费优质的图标库',
        url: 'https://nucleoapp.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/nucleoapp.png',
      },
      {
        idx: 16,
        title: 'Mesh Gradients',
        desc: '流行的网格渐变背景免费下载',
        url: 'https://lstore.graphics/meshgradients/',
        logo: 'http://chuangzaoshi.com/assets/images/D/lstore.png',
      },
      {
        idx: 17,
        title: 'UI中国',
        desc: '中国本地化UI设计展示平台',
        url: 'http://www.ui.cn/',
        logo: 'http://chuangzaoshi.com/assets/images/D/ui.cn.png',
      },
      {
        idx: 18,
        title: '大邦创新',
        desc: '创新型用户体验设计公司',
        url: 'http://www.bigbang-consulting.com',
        logo: 'http://chuangzaoshi.com/assets/images/D/bigbang-consulting.png',
      },
      {
        idx: 19,
        title: 'manypixels',
        desc: '免版权小人场景矢量插画素材',
        url: 'https://gallery.manypixels.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/manypixels.png',
      },
    ],
  },
  {
    idx: 1,
    title: '灵感采集',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'Muzli',
        desc: '设计灵感资源聚合',
        url: 'http://muz.li/',
        logo: 'http://chuangzaoshi.com/assets/images/D/muzli.png',
      },
      {
        idx: 1,
        title: 'Pinterest',
        desc: '全球美图收藏采集站',
        url: 'https://www.pinterest.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pinterest.png',
      },
      {
        idx: 2,
        title: 'Panda',
        desc: '设计作品和资讯文摘订阅平台',
        url: 'http://usepanda.com/app/',
        logo: 'http://chuangzaoshi.com/assets/images/D/panda.png',
      },
      {
        idx: 3,
        title: '花瓣',
        desc: '中国美图收藏采集站',
        url: 'http://huaban.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/huaban.png',
      },
      {
        idx: 4,
        title: 'FWA',
        desc: '创意媒体艺术设计作品展',
        url: 'https://thefwa.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/thefwa.png',
      },
      {
        idx: 5,
        title: 'Deviantart',
        desc: '分享各类艺术创作的设计社区',
        url: 'http://www.deviantart.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/deviantart.png',
      },
      {
        idx: 6,
        title: '365designers',
        desc: '365天每天推荐一个设计师作品',
        url: 'http://365awesomedesigners.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/365awesomedesigners.png',
      },
      {
        idx: 7,
        title: 'abduzeedo',
        desc: '创意灵感和教程的设计博客',
        url: 'http://abduzeedo.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/abduzeedo.png',
      },
      {
        idx: 8,
        title: 'Bestfolios',
        desc: '产品丨界面丨插画灵感设计画廊',
        url: 'http://bestfolios.com/main',
        logo: 'http://chuangzaoshi.com/assets/images/D/bestfolios.png',
      },
      {
        idx: 9,
        title: 'Land-book',
        desc: '精挑细选的美站收集',
        url: 'https://land-book.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/land-book.png',
      },
      {
        idx: 10,
        title: '淘靈感',
        desc: '台湾灵感创意视觉资讯收集网',
        url: 'https://www.mydesy.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/mydesy.png',
      },
      {
        idx: 11,
        title: 'CSS设计奖',
        desc: '全球优秀CSS网页设计奖提名网',
        url: 'http://www.cssdesignawards.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/cssdesignawards.png',
      },
      {
        idx: 12,
        title: 'SpirationGrid',
        desc: '创意灵感收录集合',
        url: 'http://theinspirationgrid.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/theinspirationgrid.png',
      },
    ],
  },
  {
    idx: 2,
    title: '界面交互',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'Reeoo',
        desc: '全球最火热的酷站画廊',
        url: 'http://reeoo.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/reeoo.png',
      },
      {
        idx: 1,
        title: 'UImovement',
        desc: '移动界面UI动效展示',
        url: 'https://uimovement.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uimovement.png',
      },
      {
        idx: 2,
        title: 'ElastiCode',
        desc: '优秀APP交互动效收集',
        url: 'http://www.elasticode.com/allapps.php',
        logo: 'http://chuangzaoshi.com/assets/images/D/elasticode.png',
      },
      {
        idx: 3,
        title: 'UIinteractions',
        desc: '动态效果展示',
        url: 'https://uiinteractions.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uiinteractions.png',
      },
      {
        idx: 4,
        title: '4DB',
        desc: '日本网页设计风格展',
        url: 'http://4db.cc/',
        logo: 'http://chuangzaoshi.com/assets/images/D/4db.png',
      },
      {
        idx: 5,
        title: 'Freshdesign',
        desc: 'MG动态效果展示',
        url: 'http://freshdesign.io/',
        logo: 'http://chuangzaoshi.com/assets/images/D/freshdesign.png',
      },
      {
        idx: 6,
        title: 'Pttrns',
        desc: '专业收集APP截图的网站',
        url: 'http://pttrns.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pttrns.png',
      },
      {
        idx: 7,
        title: 'collectUI',
        desc: '设计师灵感设计案例作品的站点',
        url: 'http://collectui.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/collectui.png',
      },
      {
        idx: 8,
        title: 'uplabs',
        desc: '采集前端作品设计、iOS UI设计',
        url: 'https://www.uplabs.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uplabs.png',
      },
      {
        idx: 9,
        title: 'OnePageLove',
        desc: '网站和APP单页界面欣赏',
        url: 'https://onepagelove.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/onepagelove.png',
      },
      {
        idx: 10,
        title: 'Awwwards',
        desc: '为精美及创意的设计UI颁奖站点',
        url: 'http://www.awwwards.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/awwwards.png',
      },
      {
        idx: 11,
        title: 'Freebiesbug',
        desc: '高质量设计网站、资源聚合站点',
        url: 'http://freebiesbug.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/freebiesbug.png',
      },
      {
        idx: 12,
        title: 'UIgarage',
        desc: 'UI灵感收集聚合站点',
        url: 'https://uigarage.net/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uigarage.png',
      },
      {
        idx: 13,
        title: 'littlebigdetails',
        desc: '设计细节动效灵感分享网站',
        url: 'http://littlebigdetails.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/littlebigdetails.png',
      },
      {
        idx: 14,
        title: 'Calltoidea',
        desc: '收集优秀UI组件元素设计的站点',
        url: 'http://www.calltoidea.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/calltoidea.png',
      },
      {
        idx: 15,
        title: 'muuuuu',
        desc: '日本漂亮的酷站收集[需翻墙]',
        url: 'http://muuuuu.org/',
        logo: 'http://chuangzaoshi.com/assets/images/D/muuuuu.png',
      },
      {
        idx: 16,
        title: 'Noteloop',
        desc: '收集科幻电影场景里UI交互界面',
        url: 'https://www.noteloop.com/kit/fui/',
        logo: 'http://chuangzaoshi.com/assets/images/D/noteloop.png',
      },
      {
        idx: 17,
        title: 'sitesee',
        desc: '收录漂亮的界面设计网站',
        url: 'https://sitesee.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/sitesee.png',
      },
      {
        idx: 18,
        title: 'BestWebsite',
        desc: '漂亮的酷站收集展示',
        url: 'https://bestwebsite.gallery/',
        logo: 'http://chuangzaoshi.com/assets/images/D/bestwebsite.png',
      },
      {
        idx: 19,
        title: 'Straightline',
        desc: '日式风格设计网页收录展示',
        url: 'http://bm.straightline.jp/',
        logo: 'http://chuangzaoshi.com/assets/images/D/straightline.png',
      },
      {
        idx: 20,
        title: 'webdesignclip',
        desc: '丰富的日式响应式设计收录站点',
        url: 'http://www.webdesignclip.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/webdesignclip.png',
      },
      {
        idx: 21,
        title: 'CSSwinner',
        desc: '优秀CSS网站界面和交互设计获奖作品',
        url: 'http://www.csswinner.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/csswinner.png',
      },
      {
        idx: 22,
        title: 'SiteinSpire',
        desc: '优秀网页设计展示平台',
        url: 'https://www.siteinspire.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/siteinspire.png',
      },
      {
        idx: 23,
        title: 'UseYourInterface',
        desc: '界面交互响应设计收录网站',
        url: 'http://useyourinterface.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/useyourinterface.png',
      },
      {
        idx: 24,
        title: 'lovelyUI',
        desc: '可爱的UI手机界面设计搜集',
        url: 'http://www.lovelyui.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/lovelyui.png',
      },
    ],
  },
  {
    idx: 3,
    title: '设计规范',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'Android设计',
        desc: '安卓官方设计指南',
        url: 'https://developer.android.com/design/index.html',
        logo: 'http://chuangzaoshi.com/assets/images/D/android.png',
      },
      {
        idx: 1,
        title: '安卓尺寸',
        desc: 'Google安卓主流设备尺寸',
        url: 'https://material.io/devices/',
        logo: 'http://chuangzaoshi.com/assets/images/D/android-screen.png',
      },
      {
        idx: 2,
        title: 'Apple设计',
        desc: '苹果官方设计指南',
        url: 'https://developer.apple.com/design/',
        logo: 'http://chuangzaoshi.com/assets/images/D/apple.png',
      },
      {
        idx: 3,
        title: 'Screensiz',
        desc: '移动屏幕尺寸规范',
        url: 'http://screensiz.es/phone',
        logo: 'http://chuangzaoshi.com/assets/images/D/screensiz.png',
      },
      {
        idx: 4,
        title: 'Google设计',
        desc: '谷歌官方设计指南',
        url: 'https://design.google.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/google.png',
      },
      {
        idx: 5,
        title: 'Material设计',
        desc: 'MaterialDesign设计官方指南',
        url: 'https://material.io/',
        logo: 'http://chuangzaoshi.com/assets/images/D/material.png',
      },
      {
        idx: 6,
        title: 'Modern设计',
        desc: '微软Modern官方设计语言',
        url: 'https://www.microsoft.com/en-us/design',
        logo: 'http://chuangzaoshi.com/assets/images/D/modern.png',
      },
      {
        idx: 7,
        title: 'Android设计·中国',
        desc: '安卓官方设计指南中国版·不用翻墙',
        url: 'https://developer.android.google.cn/design/index.html',
        logo: 'http://chuangzaoshi.com/assets/images/D/android.png',
      },
      {
        idx: 8,
        title: 'WEUI',
        desc: '微信官方小程序UI样式库',
        url: 'https://weui.io/',
        logo: 'http://chuangzaoshi.com/assets/images/C/weui.png',
      },
      {
        idx: 9,
        title: 'iPhone尺寸',
        desc: 'iPhone各设备屏幕尺寸信息参数',
        url: 'https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions',
        logo: 'http://chuangzaoshi.com/assets/images/D/paintcodeapp.png',
      },
      {
        idx: 10,
        title: 'Fluent Design',
        desc: 'Window10全新设计语言',
        url: 'https://www.microsoft.com/design/fluent/',
        logo: 'http://chuangzaoshi.com/assets/images/D/fluent.png',
      },
    ],
  },
  {
    idx: 4,
    title: '在线工具',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'CloudConvert',
        desc: '云端在线图片格式转换',
        url: 'https://cloudconvert.org/',
        logo: 'http://chuangzaoshi.com/assets/images/D/cloudconvert.png',
      },
      {
        idx: 1,
        title: 'TinyPng',
        desc: '超完美PNG压缩工具',
        url: 'https://tinypng.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/tinypng.png',
      },
      {
        idx: 2,
        title: 'FindMyfont',
        desc: '英文上传图片查找字体',
        url: 'http://www.myfonts.com/WhatTheFont/',
        logo: 'http://chuangzaoshi.com/assets/images/D/myfonts.png',
      },
      {
        idx: 3,
        title: 'qiuziti',
        desc: '中文上传图片字体查找',
        url: 'http://www.qiuziti.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/qiuziti.png',
      },
      {
        idx: 4,
        title: 'PxCook',
        desc: '高效易用的自动标注工具',
        url: 'http://fancynode.com.cn/pxcook',
        logo: 'http://chuangzaoshi.com/assets/images/D/pxcook.png',
      },
      {
        idx: 5,
        title: 'Jpegmini',
        desc: 'JPG图片压缩工具',
        url: 'http://www.jpegmini.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/jpegmini.png',
      },
      {
        idx: 6,
        title: 'Smallpdf',
        desc: '专注于PDF格式互转、压缩等功能',
        url: 'https://smallpdf.com/cn',
        logo: 'http://chuangzaoshi.com/assets/images/D/smallpdf.png',
      },
      {
        idx: 7,
        title: 'Logojoy',
        desc: '根据条件匹配在线生成Logo',
        url: 'http://logojoy.com/app.php',
        logo: 'http://chuangzaoshi.com/assets/images/D/logojoy.png',
      },
      {
        idx: 8,
        title: 'Bezier Game',
        desc: '贝塞尔曲线练习',
        url: 'http://bezier.method.ac/',
        logo: 'http://chuangzaoshi.com/assets/images/D/bezier.png',
      },
      {
        idx: 9,
        title: 'PDFcandy',
        desc: '汇集众多常用PDF在线工具',
        url: 'https://pdfcandy.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pdfcandy.png',
      },
      {
        idx: 10,
        title: 'QRhacker',
        desc: '国外创建二维码在线应用',
        url: 'http://www.qrhacker.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/qrhacker.png',
      },
      {
        idx: 11,
        title: '草料二维码',
        desc: '国内创建二维码在线应用',
        url: 'https://cli.im/',
        logo: 'http://chuangzaoshi.com/assets/images/D/cli.png',
      },
      {
        idx: 12,
        title: 'optimizilla',
        desc: '支持JPEG和PNG格式在线压缩工具',
        url: 'http://optimizilla.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/optimizilla.png',
      },
      {
        idx: 13,
        title: 'waifu2x',
        desc: '图片智能算法无损放大',
        url: 'http://waifu2x.udp.jp/',
        logo: 'http://chuangzaoshi.com/assets/images/D/waifu2x.png',
      },
      {
        idx: 14,
        title: 'VectorMagic',
        desc: '收费！非常强大的位图转矢量图',
        url: 'https://vectormagic.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/vectormagic.png',
      },
      {
        idx: 15,
        title: 'FlattyShadow',
        desc: '图标长投影在线生成',
        url: 'http://flattyshadow.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/flattyshadow.png',
      },
      {
        idx: 16,
        title: 'WeaveSilk',
        desc: '炫酷对称艺术纹理特效绘制',
        url: 'http://weavesilk.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/weavesilk.png',
      },
      {
        idx: 17,
        title: 'QuickMark',
        desc: '台湾一家二维码在线制作和APP程序',
        url: 'http://www.quickmark.com.tw/cht/qrcode-datamatrix-generator/',
        logo: 'http://chuangzaoshi.com/assets/images/D/quickmark.png',
      },
      {
        idx: 18,
        title: 'Autodraw',
        desc: '谷歌绘画智能匹配相应图形[需翻墙]',
        url: 'https://autodraw.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/autodraw.png',
      },
      {
        idx: 19,
        title: 'Grid',
        desc: '网页网格栅格化工具',
        url: 'http://grid.guide/',
        logo: 'http://chuangzaoshi.com/assets/images/D/grid.png',
      },
      {
        idx: 20,
        title: 'Loading',
        desc: '制作GIF丨SVG丨CSS加载动画图标',
        url: 'https://loading.io/',
        logo: 'http://chuangzaoshi.com/assets/images/D/loading.png',
      },
      {
        idx: 21,
        title: 'Logaster',
        desc: '在线免费创建简单logo及名片设计',
        url: 'https://www.logaster.cn',
        logo: 'http://chuangzaoshi.com/assets/images/D/logaster.png',
      },
      {
        idx: 22,
        title: 'Goimg.io',
        desc: '智能在线图片压缩',
        url: 'https://goimg.io/',
        logo: 'http://chuangzaoshi.com/assets/images/F/goimg.png',
      },
      {
        idx: 23,
        title: 'Preloaders',
        desc: 'Loading加载动画在线制作',
        url: 'https://icons8.com/preloaders/',
        logo: 'http://chuangzaoshi.com/assets/images/D/preloaders.png',
      },
      {
        idx: 24,
        title: 'ClippingMagic',
        desc: '在线抠图工具',
        url: 'https://clippingmagic.com',
        logo: 'http://chuangzaoshi.com/assets/images/D/clippingmagic.png',
      },
      {
        idx: 25,
        title: 'Squoosh',
        desc: 'Google在线优化压缩图片(支持webp)',
        url: 'https://squoosh.app/',
        logo: 'http://chuangzaoshi.com/assets/images/D/squoosh.png',
      },
      {
        idx: 26,
        title: 'Photopea',
        desc: '在线打开PSD丨Sketch丨Gimp编辑器',
        url: 'https://www.photopea.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/photopea.png',
      },
      {
        idx: 27,
        title: '鹿班',
        desc: '阿里人工智能电商Banner广告图制作',
        url: 'https://luban.aliyun.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/luban.png',
      },
    ],
  },
  {
    idx: 5,
    title: 'icon图标',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'icomoon',
        desc: '矢量图打包成图标字体的技术平台',
        url: 'https://icomoon.io/',
        logo: 'http://chuangzaoshi.com/assets/images/D/icomoon.png',
      },
      {
        idx: 1,
        title: 'iconfont',
        desc: '阿里团队图标字体及图标素材下载平台',
        url: 'http://www.iconfont.cn/plus',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconfont.png',
      },
      {
        idx: 2,
        title: 'Easyicon',
        desc: '图标搜索大全',
        url: 'http://www.easyicon.net/',
        logo: 'http://chuangzaoshi.com/assets/images/D/easyicon.png',
      },
      {
        idx: 3,
        title: 'TheNounProject',
        desc: '高质量图标下载',
        url: 'https://thenounproject.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/thenounproject.png',
      },
      {
        idx: 4,
        title: 'iconfinder',
        desc: '高质量付费图标下载',
        url: 'https://www.iconfinder.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconfinder.png',
      },
      {
        idx: 5,
        title: 'themify',
        desc: '一套免费特色iconfont图标支持WP插件',
        url: 'http://themify.me/themify-icons',
        logo: 'http://chuangzaoshi.com/assets/images/D/themify.png',
      },
      {
        idx: 6,
        title: 'iconmonstr',
        desc: '精美免费简洁icon',
        url: 'http://iconmonstr.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconmonstr.png',
      },
      {
        idx: 7,
        title: 'Logodust',
        desc: '特赞！提供开源免费的LOGO',
        url: 'http://logodust.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/logodust.png',
      },
      {
        idx: 8,
        title: 'Iconjar',
        desc: '免费图标素材管理工具',
        url: 'http://geticonjar.com/freebies',
        logo: 'http://chuangzaoshi.com/assets/images/D/geticonjar.png',
      },
      {
        idx: 9,
        title: 'Flaticon',
        desc: '海量扁平化免费的图标库',
        url: 'http://www.flaticon.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/flaticon.png',
      },
      {
        idx: 10,
        title: 'iconstore',
        desc: '免费商用的高质量图标素材站',
        url: 'http://iconstore.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconstore.png',
      },
      {
        idx: 11,
        title: 'Logoeps',
        desc: '各大国际品牌logo矢量图',
        url: 'http://www.logoeps.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/logoeps.png',
      },
      {
        idx: 12,
        title: 'IOSicongallery',
        desc: 'IOS平台APP图标收录和欣赏',
        url: 'http://iosicongallery.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iosicongallery.png',
      },
      {
        idx: 13,
        title: 'Emojione',
        desc: 'Emoji表情图标整理',
        url: 'http://emojione.com/demo/',
        logo: 'http://chuangzaoshi.com/assets/images/D/emojione.png',
      },
      {
        idx: 14,
        title: 'iconninja',
        desc: '海量图标搜索可生成css sprites',
        url: 'http://www.iconninja.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconninja.png',
      },
      {
        idx: 15,
        title: 'icons8',
        desc: '系统平台风格和web图标库',
        url: 'https://icons8.com/web-app/new-icons/all',
        logo: 'http://chuangzaoshi.com/assets/images/D/icons8.png',
      },
      {
        idx: 16,
        title: 'iconsfeed',
        desc: 'iOS系统应用图标收集和分享',
        url: 'http://www.iconsfeed.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconsfeed.png',
      },
      {
        idx: 17,
        title: 'CSSGG',
        desc: '开源免icon，SVG动画，图标样式组件等',
        url: 'https://css.gg/',
        logo: 'http://chuangzaoshi.com/assets/images/D/css.gg.png',
      },
      {
        idx: 18,
        title: '草莓图标',
        desc: '为开发者设计的一套免费开源图标库',
        url: 'http://chuangzaoshi.com/icon/',
        logo: 'http://chuangzaoshi.com/assets/images/D/caomei.png',
      },
      {
        idx: 19,
        title: 'IKonate',
        desc: '完全可定制和使用的矢量图标库',
        url: 'http://ikonate.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/ikonate.png',
      },
      {
        idx: 20,
        title: 'logolab',
        desc: '帮设计师只管检查logo的工具',
        url: 'https://logolab.app/home',
        logo: 'http://chuangzaoshi.com/assets/images/D/logolab.png',
      },
      {
        idx: 21,
        title: 'UseAnimations',
        desc: '一套微型的图标动态效果库',
        url: 'https://useanimations.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/useanimations.png',
      },
      {
        idx: 22,
        title: 'Flight icon',
        desc: '一套界面中的图标动态效果包',
        url: 'https://www.flighticon.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/flighticon.png',
      },
      {
        idx: 23,
        title: 'Nucleo',
        desc: '免费优质的图标库',
        url: 'https://nucleoapp.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/nucleoapp.png',
      },
      {
        idx: 24,
        title: 'iconshock',
        desc: '2百万专业的图标库（付费为主）',
        url: 'https://www.iconshock.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconshock.png',
      },
    ],
  },
  {
    idx: 6,
    title: '设计素材',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'Freepik',
        desc: '免费高质量矢量图下载',
        url: 'http://www.freepik.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/freepik.png',
      },
      {
        idx: 1,
        title: 'Subtlepatterns',
        desc: '简洁大气的背景纹理素材',
        url: 'http://subtlepatterns.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/subtlepatterns.png',
      },
      {
        idx: 2,
        title: 'Shutterstock',
        desc: '全球最大的设计素材收费库',
        url: 'http://www.shutterstock.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/shutterstock.png',
      },
      {
        idx: 3,
        title: 'Firmbee',
        desc: 'Firmbee精品设备和场景mockup素材',
        url: 'https://firmbee.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/firmbee.png',
      },
      {
        idx: 4,
        title: 'Mockup',
        desc: '收费高质量的专业mockup模板',
        url: 'https://mockup.zone/',
        logo: 'http://chuangzaoshi.com/assets/images/D/mockup.png',
      },
      {
        idx: 5,
        title: 'Dunnnk',
        desc: '智能设备场景模板下载',
        url: 'http://dunnnk.com/',
        logo: 'http://chuangzaoshi.com/assets/images/logo.png',
      },
      {
        idx: 6,
        title: 'Graphictwister',
        desc: '平面海报、设备场景模板下载',
        url: 'https://graphictwister.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/graphictwister.png',
      },
      {
        idx: 7,
        title: 'Canva',
        desc: '海报模板输出设计',
        url: 'https://www.canva.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/canva.png',
      },
      {
        idx: 8,
        title: 'Themeforest',
        desc: '主题森林-全球UI作品出售平台',
        url: 'https://themeforest.net/',
        logo: 'http://chuangzaoshi.com/assets/images/D/themeforest.png',
      },
      {
        idx: 9,
        title: 'UI8',
        desc: '漂亮的商业UI模板售卖平台',
        url: 'https://ui8.net/',
        logo: 'http://chuangzaoshi.com/assets/images/D/ui8.png',
      },
      {
        idx: 10,
        title: 'Fribbble',
        desc: 'Dribbble上一些免费的设计PSD源文件',
        url: 'http://www.fribbble.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/fribbble.png',
      },
      {
        idx: 11,
        title: 'Sketch.im',
        desc: '国内不错的Sketch站点资源',
        url: 'http://sketch.cm/',
        logo: 'http://chuangzaoshi.com/assets/images/D/sketchim.png',
      },
      {
        idx: 12,
        title: 'Texturer',
        desc: '3D建模纹理特效素材',
        url: 'http://texturer.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/texturer.png',
      },
      {
        idx: 13,
        title: 'CSSauthor',
        desc: '对设计和开发有帮助的优质设计资源',
        url: 'http://www.cssauthor.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/cssauthor.png',
      },
      {
        idx: 14,
        title: 'Principlerepo',
        desc: '高质量Principle原型丨动效设计资源',
        url: 'http://principlerepo.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/principlerepo.png',
      },
      {
        idx: 15,
        title: '千图网',
        desc: '海量原创设计模板免费下载',
        url: 'http://www.58pic.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/58pic.png',
      },
      {
        idx: 16,
        title: '昵图网',
        desc: '国内海量平面免费素材下载',
        url: 'http://www.nipic.com/index.html',
        logo: 'http://chuangzaoshi.com/assets/images/D/nipic.png',
      },
      {
        idx: 17,
        title: '素材中国',
        desc: '海量免费素材共享平台',
        url: 'http://www.sccnn.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/sccnn.png',
      },
      {
        idx: 18,
        title: 'PatternLibrary',
        desc: '随机下拉背景纹理酷',
        url: 'http://thepatternlibrary.com',
        logo: 'http://chuangzaoshi.com/assets/images/D/thepatternlibrary.png',
      },
      {
        idx: 19,
        title: 'SketchHunt',
        desc: 'Sketch设计素材资源、插件和教程',
        url: 'http://sketchhunt.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/sketchhunt.png',
      },
      {
        idx: 20,
        title: 'Vecteezy',
        desc: '免费矢量素材搜索和下载',
        url: 'https://www.vecteezy.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/vecteezy.png',
      },
      {
        idx: 21,
        title: 'HeroPatterns',
        desc: '矢量和CSS网页背景纹理配色生成',
        url: 'http://www.heropatterns.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/heropatterns.png',
      },
      {
        idx: 22,
        title: 'Pixeden',
        desc: '免费高质量设计素材模板分享',
        url: 'http://www.pixeden.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pixeden.png',
      },
      {
        idx: 23,
        title: 'GraphicsFuel',
        desc: '国外免费设计素材模板下载站',
        url: 'http://www.graphicsfuel.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/graphicsfuel.png',
      },
    ],
  },
  {
    idx: 7,
    title: '图库素材',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'ZoommyAPP',
        desc: '聚合各大免费高清图库的APP',
        url: 'http://zoommyapp.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/zoommyapp.png',
      },
      {
        idx: 1,
        title: 'Unsplash',
        desc: '高质量免费版权的图库素材',
        url: 'https://unsplash.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/unsplash.png',
      },
      {
        idx: 2,
        title: 'Startupstockp',
        desc: '初创公司精品免费图库',
        url: 'http://startupstockphotos.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/startupstockp.png',
      },
      {
        idx: 3,
        title: 'Magdeleine',
        desc: '免费高清灵感图片',
        url: 'http://magdeleine.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/magdeleine.png',
      },
      {
        idx: 4,
        title: 'Splitshire',
        desc: '免费高清摄影图库',
        url: 'https://www.splitshire.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/splitshire.png',
      },
      {
        idx: 5,
        title: 'Pexels',
        desc: '精品免费图库分享',
        url: 'https://www.pexels.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pexels.png',
      },
      {
        idx: 6,
        title: 'Flickr',
        desc: '雅虎旗下摄影师图片分享网站',
        url: 'https://www.flickr.com/explore',
        logo: 'http://chuangzaoshi.com/assets/images/D/flickr.png',
      },
      {
        idx: 7,
        title: '500px',
        desc: '全球著名摄影师图片展示和售卖平台',
        url: 'https://500px.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/500px.png',
      },
      {
        idx: 8,
        title: 'FoodiesFeed',
        desc: '专注于免费食品图片素材的分享',
        url: 'https://foodiesfeed.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/foodiesfeed.png',
      },
      {
        idx: 9,
        title: 'Pixabay',
        desc: '免费的高清图片、矢量图片、艺术插花',
        url: 'https://pixabay.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pixabay.png',
      },
      {
        idx: 10,
        title: 'Pakutaso',
        desc: '日式照片素材免费分享站点',
        url: 'https://www.pakutaso.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pakutaso.png',
      },
      {
        idx: 11,
        title: 'Stocksnap',
        desc: '每周免版权高清图片分享',
        url: 'https://stocksnap.io/',
        logo: 'http://chuangzaoshi.com/assets/images/D/stocksnap.png',
      },
      {
        idx: 12,
        title: 'Hellorf',
        desc: '站酷海洛创意收费正版图库',
        url: 'http://www.hellorf.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/hellorf.png',
      },
      {
        idx: 13,
        title: '123rf',
        desc: '企业摄影和创意素材正版图片库网',
        url: 'http://www.123rf.com.cn/',
        logo: 'http://chuangzaoshi.com/assets/images/D/123rf.png',
      },
      {
        idx: 14,
        title: 'BingGallery',
        desc: '微软必应搜索精美壁纸画廊',
        url: 'http://www.bing.com/gallery/',
        logo: 'http://chuangzaoshi.com/assets/images/D/binggallery.png',
      },
      {
        idx: 15,
        title: 'HDwallpapers',
        desc: '高清壁纸图片分享网站',
        url: 'https://www.hdwallpapers.net/',
        logo: 'http://chuangzaoshi.com/assets/images/D/hdwallpapers.png',
      },
    ],
  },
  {
    idx: 8,
    title: '颜色搭配',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'AdobeColor',
        desc: 'Adobe专业配色工具',
        url: 'https://color.adobe.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/adobecolor.png',
      },
      {
        idx: 1,
        title: 'Nipponcolors',
        desc: '日本古典传统配色网站',
        url: 'http://nipponcolors.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/nipponcolors.png',
      },
      {
        idx: 2,
        title: 'Colorfavs',
        desc: '上传并匹配提取图片风格的颜色',
        url: 'http://www.colorfavs.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/colorfavs.png',
      },
      {
        idx: 3,
        title: 'Coolors',
        desc: '在线快速配色生成工具',
        url: 'https://coolors.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/coolors.png',
      },
      {
        idx: 4,
        title: 'Colorhunt',
        desc: '每天更新一组简洁舒服的配色方案',
        url: 'http://www.colorhunt.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/colorhunt.png',
      },
      {
        idx: 5,
        title: 'MD调色器',
        desc: 'MaterialDesign强大的在线配色',
        url: 'https://www.materialpalette.com/blue/purple',
        logo: 'http://chuangzaoshi.com/assets/images/D/materialpalette.png',
      },
      {
        idx: 6,
        title: 'webgradients',
        desc: 'itmeo旗下180个漂亮渐变色模板',
        url: 'https://webgradients.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/webgradients.png',
      },
      {
        idx: 7,
        title: 'Trianglify',
        desc: '炫酷多边形背景色块生成',
        url: 'http://qrohlf.com/trianglify-generator/',
        logo: 'http://chuangzaoshi.com/assets/images/D/trianglifygenerator.png',
      },
      {
        idx: 8,
        title: 'ColourLovers',
        desc: '全球设计师色彩分享交流社区',
        url: 'http://www.colourlovers.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/colourlovers.png',
      },
      {
        idx: 9,
        title: 'WebColourData',
        desc: '通过网址获取分析网站配色',
        url: 'http://webcolourdata.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/webcolourdata.png',
      },
      {
        idx: 10,
        title: '中国传统色',
        desc: '中科院色谱的中国传统色',
        url: 'http://zhongguose.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/zhongguose.png',
      },
      {
        idx: 11,
        title: 'Mesh Gradients',
        desc: '流行的网格渐变背景免费下载',
        url: 'https://lstore.graphics/meshgradients/',
        logo: 'http://chuangzaoshi.com/assets/images/D/lstore.png',
      },
      {
        idx: 12,
        title: 'Picular',
        desc: '色彩搜索引擎',
        url: 'https://picular.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/picular.png',
      },
    ],
  },
  {
    idx: 9,
    title: '字体字形',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: '第一字体转换器',
        desc: '在线字体生成预览转换',
        url: 'http://www.diyiziti.com/Download/209/',
        logo: 'http://chuangzaoshi.com/assets/images/D/diyiziti.png',
      },
      {
        idx: 1,
        title: 'Fontsup',
        desc: '免费英文字体下载库',
        url: 'https://fontsup.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/fontsup.png',
      },
      {
        idx: 2,
        title: 'Fonts2u',
        desc: '详细分类免费字体搜索下载库',
        url: 'http://zh.fonts2u.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/fonts2u.png',
      },
      {
        idx: 3,
        title: 'Urbanfonts',
        desc: '免费英文字体搜索下载站',
        url: 'https://www.urbanfonts.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/urbanfonts.png',
      },
      {
        idx: 4,
        title: 'myfonts',
        desc: '最新时尚的商业英文字体',
        url: 'http://www.myfonts.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/myfonts.png',
      },
      {
        idx: 5,
        title: '苹方字体',
        desc: '苹果最新的系统界面字体San Francisco',
        url: 'https://developer.apple.com/fonts/',
        logo: 'http://chuangzaoshi.com/assets/images/D/apple.png',
      },
      {
        idx: 6,
        title: '思源黑体',
        desc: 'Adobe、Google出品的开源中文黑体',
        url: 'https://typekit.com/fonts/source-han-sans-simplified-chinese',
        logo: 'http://chuangzaoshi.com/assets/images/D/siyuanheiti.png',
      },
      {
        idx: 7,
        title: 'Comicneue',
        desc: '免费手写可爱字体官网下载',
        url: 'http://comicneue.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/comicneue.png',
      },
      {
        idx: 8,
        title: 'Typekit',
        desc: 'Adobe出品的web在线字库',
        url: 'https://typekit.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/typekit.png',
      },
      {
        idx: 9,
        title: '思源宋体',
        desc: 'Adobe、Google出品的开源中文宋体',
        url: 'https://source.typekit.com/source-han-serif/',
        logo: 'http://chuangzaoshi.com/assets/images/D/siyuanheiti.png',
      },
      {
        idx: 10,
        title: '360查字体',
        desc: '查版权，免纠纷',
        url: 'https://fonts.safe.360.cn/',
        logo: 'http://chuangzaoshi.com/assets/images/D/360.png',
      },
    ],
  },
  {
    idx: 10,
    title: '学习教程',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'Medium',
        desc: '国外精美的设计文章欣赏',
        url: 'https://medium.design/',
        logo: 'http://chuangzaoshi.com/assets/images/D/medium.png',
      },
      {
        idx: 1,
        title: 'sketchchina',
        desc: 'sketch中国资源插件分享社区',
        url: 'http://www.sketchchina.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/sketchchina.png',
      },
      {
        idx: 2,
        title: 'AnywayFM',
        desc: '设计经验、历程杂谈的一款播客节目',
        url: 'http://anyway.fm/',
        logo: 'http://chuangzaoshi.com/assets/images/D/anyway.png',
      },
      {
        idx: 3,
        title: '优设',
        desc: '国内设计师教程分享文章',
        url: 'http://www.uisdc.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uisdc.png',
      },
      {
        idx: 4,
        title: 'Envato教程',
        desc: 'Envato时尚设计效果教程',
        url: 'https://design.tutsplus.com/tutorials',
        logo: 'http://chuangzaoshi.com/assets/images/D/envato.png',
      },
      {
        idx: 5,
        title: 'UX Coffee 设计咖',
        desc: '关注产品设计和注用户体验FM播客',
        url: 'http://podcast.uxcoffee.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uxcoffee.png',
      },
      {
        idx: 6,
        title: '字谈字畅',
        desc: '华语字体排印主题FM播客节目',
        url: 'http://www.lizhi.fm/1852153/',
        logo: 'http://chuangzaoshi.com/assets/images/D/typeisbeautiful.png',
      },
      {
        idx: 7,
        title: '图月志',
        desc: 'JJYing的界面设计个人博客',
        url: 'http://iconmoon.com/blog2/',
        logo: 'http://chuangzaoshi.com/assets/images/D/iconmoon.png',
      },
      {
        idx: 8,
        title: 'Heydesigner',
        desc: '设计师和前端开发者的美文收录',
        url: 'http://heydesigner.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/heydesigner.png',
      },
      {
        idx: 9,
        title: 'webdesignerdepot',
        desc: '网页设计教程和文章学习平台',
        url: 'http://www.webdesignerdepot.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/webdesignerdepot.png',
      },
      {
        idx: 10,
        title: 'Textuts',
        desc: '专注于Text文字特效教程收录',
        url: 'http://textuts.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/textuts.png',
      },
      {
        idx: 11,
        title: '异能电台',
        desc: '话题非常广的设计师FM播客',
        url: 'https://www.yineng.fm/',
        logo: 'http://chuangzaoshi.com/assets/images/D/yineng.png',
      },
      {
        idx: 12,
        title: 'Gigantic',
        desc: '卡通角色插画设计教程(YouTube频道)',
        url: 'www.gigantic.click',
        logo: 'http://chuangzaoshi.com/assets/images/D/gigantic.png',
      },
      {
        idx: 13,
        title: 'DesignerNews',
        desc: '最前沿的设计师行业资讯',
        url: 'https://www.designernews.co/',
        logo: 'http://chuangzaoshi.com/assets/images/D/designernews.png',
      },
      {
        idx: 14,
        title: 'PixelJoint',
        desc: '像素艺术爱好者交流学习社区',
        url: 'http://pixeljoint.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/pixeljoint.png',
      },
      {
        idx: 15,
        title: 'DesignToday',
        desc: '英文设计文章精选集合站',
        url: 'https://www.designtoday.io/',
        logo: 'http://chuangzaoshi.com/assets/images/D/designtoday.png',
      },
      {
        idx: 16,
        title: 'Smashing',
        desc: 'WEB设计开发杂志博客',
        url: 'https://www.smashingmagazine.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/smashingmagazine.png',
      },
    ],
  },
  {
    idx: 11,
    title: '设计团队',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'eicodesign',
        desc: '国内专业界设计团队',
        url: 'http://eicodesign.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/eicodesign.png',
      },
      {
        idx: 1,
        title: '腾讯ISUX',
        desc: '社交用户体验设计',
        url: 'https://isux.tencent.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/isuxtencent.png',
      },
      {
        idx: 2,
        title: '腾讯CDC',
        desc: '腾讯用户研究与体验设计中心',
        url: 'http://cdc.tencent.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/cdctencent.png',
      },
      {
        idx: 3,
        title: '腾讯MXD',
        desc: '移动互联网设计中心',
        url: 'http://mxd.tencent.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/mxdtencent.png',
      },
      {
        idx: 4,
        title: '阿里巴巴',
        desc: '阿里巴巴用户体验设计部',
        url: 'http://www.aliued.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/alibaba.png',
      },
      {
        idx: 5,
        title: '阿里妈妈MUX',
        desc: '阿里妈妈MUX',
        url: 'http://mux.alimama.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/alimama.png',
      },
      {
        idx: 6,
        title: 'Frog设计',
        desc: '跨国设计与战略咨询公司',
        url: 'http://www.frogdesign.cn/',
        logo: 'http://chuangzaoshi.com/assets/images/D/frogdesign.png',
      },
      {
        idx: 7,
        title: '新浪UED',
        desc: '新浪用户体验设计部',
        url: 'http://ued.sina.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/sinaued.png',
      },
      {
        idx: 8,
        title: '百度EUX',
        desc: '百度企业产品用户中心',
        url: 'http://eux.baidu.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/baidueux.png',
      },
      {
        idx: 9,
        title: '网易GUX',
        desc: '网易游戏用户体验中心',
        url: 'http://gux.163.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/wangyigux.png',
      },
      {
        idx: 10,
        title: '百度MUX',
        desc: '百度用户体验中心',
        url: 'http://mux.baidu.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/baidumux.png',
      },
      {
        idx: 11,
        title: 'uedc',
        desc: '网易用户体验设计中心',
        url: 'http://uedc.163.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uedc163.png',
      },
      {
        idx: 12,
        title: 'TGideas',
        desc: '腾讯游戏官方设计团队',
        url: 'http://tgideas.qq.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/tgideas.png',
      },
      {
        idx: 13,
        title: 'U一点',
        desc: '阿里巴巴用户体验设计博客',
        url: 'http://www.aliued.cn/',
        logo: 'http://chuangzaoshi.com/assets/images/D/aliued.png',
      },
      {
        idx: 14,
        title: '360UXC',
        desc: '360UXC用户体验设计中心',
        url: 'http://uxc.360.cn/',
        logo: 'http://chuangzaoshi.com/assets/images/D/uxc360.png',
      },
      {
        idx: 15,
        title: 'JDC',
        desc: '京东设计中心',
        url: 'http://jdc.jd.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/jdc.png',
      },
      {
        idx: 16,
        title: 'Tubik Studio',
        desc: '在视觉和界面领域比较有名的工作者',
        url: 'http://tubikstudio.com/',
        logo: 'http://chuangzaoshi.com/assets/images/D/tubikstudio.png',
      },
      {
        idx: 17,
        title: 'Facebook Design',
        desc: 'Facebook设计团队网站',
        url: 'http://facebook.design/',
        logo: 'http://chuangzaoshi.com/assets/images/D/facebook.png',
      },
      {
        idx: 18,
        title: '大邦创新',
        desc: '创新型用户体验设计公司',
        url: 'http://www.bigbang-consulting.com',
        logo: 'http://chuangzaoshi.com/assets/images/D/bigbang-consulting.png',
      },
    ],
  },
  {
    idx: 12,
    title: '插画绘画',
    cateEn: 'Design',
    cateCn: '设计',
    chilren: [
      {
        idx: 0,
        title: 'undraw',
        desc: '免费的UI界面，场景，人物可换颜色插画',
        url: 'https://undraw.co/illustrations',
        logo: 'http://chuangzaoshi.com/assets/images/D/zool.png',
      },
    ],
  },
];

export default async (req: IncomingMessage, res: ServerResponse) => {
  res.statusCode = 200;
  res.end(JSON.stringify(data));
};
